spring:
  application:
    name: receiver-service
server:
  port: ${SERVER_PORT}

coordinator:
  url: ${COORDINATOR_URL}

webhook:
  timestamp:
    tolerance: ${TIMESTAMP_TOLERANCE}

#logging:
#  level:
#    br.com.danilodps.receiver: DEBUG